name: release-please

on:
  workflow_call:
    outputs:
      release_created:
        description: "True if previous merged PR was a release"
        value: ${{ jobs.release-please.outputs.release_created }}
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
